DROP TABLE surovina;
DROP TABLE pecivo;
DROP TABLE predmet;
DROP TABLE objednavka;
DROP TABLE vezen;
DROP TABLE smena;
DROP TABLE zamestnanec;
DROP TABLE paserak;
DROP TABLE vezeni;

CREATE TABLE surovina
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    skladem    varchar2(256),
    cena    number
);
CREATE TABLE pecivo
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    hmotnost varchar2(256),
    alergeny varchar2(256),
    druh varchar2(256)
);
CREATE TABLE predmet
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    druh varchar2(256),
    cena number,
    hmotnost varchar2(256)
);
CREATE TABLE objednavka
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    datum_objednani date DEFAULT current_date,
    stav    varchar2(256),
    cena    varchar2(256),
    doprava varchar2(256),
    termin_dodani   date
);
CREATE TABLE vezen
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno varchar2(256),
    datum_narozeni date,
    pohlavi varchar2(256),
    cislo_cely number,
    trest varchar2(256)
);
CREATE TABLE smena
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    zacatek timestamp,
    konec timestamp,
    datum date,
    misto varchar2(256)
);
CREATE TABLE zamestnanec
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno varchar2(256),
    datum_narozeni date,
    pohlavi varchar2(256),
    ulice varchar2(256),
    cislo_popisne number,
    mesto varchar2(256),
    psc number
);
CREATE TABLE paserak
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno varchar2(256),
    datum_narozeni date,
    pohlavi varchar2(256)
);
CREATE TABLE vezeni
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    /* v ERD entita vezeni je asi spatne*/
    ulice varchar2(256),
    cislo_popisne number,
    mesto varchar2(256),
    psc number
);
/*INSERT INTO xsouce15.OBJEDNAVKA (DATUM_OBJEDNANI, STAV, CENA, DOPRAVA, TERMIN_DODANI)
VALUES (DEFAULT, null, null, 'DHL', null);*/