/*BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE surovina';
    EXECUTE IMMEDIATE 'DROP TABLE pecivo';
    EXECUTE IMMEDIATE 'DROP TABLE predmet';
    EXECUTE IMMEDIATE 'DROP TABLE objednavka';
    EXECUTE IMMEDIATE 'DROP TABLE vezen';
    EXECUTE IMMEDIATE 'DROP TABLE smena';
EXCEPTION
    WHEN OTHERS THEN NULL;
end;
*/
DROP TABLE surovina;
DROP TABLE pecivo;
DROP TABLE predmet;
DROP TABLE objednavka;
DROP TABLE vezen;
DROP TABLE smena;
DROP TABLE zamestnanec;
DROP TABLE paserak;
DROP TABLE vezeni;

DROP TABLE mnozstvi;
DROP TABLE objednavka_paserak;
DROP TABLE objednavka_predmet;
DROP TABLE objednavka_vezen;
DROP TABLE paserak_vezeni;
DROP TABLE pecivo_objednavka;
DROP TABLE smena_zamestannec;
DROP TABLE surovina_pecivo;
DROP TABLE vezeni_smena;

CREATE TABLE surovina
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    skladem    varchar2(256),
    cena    number
);
CREATE TABLE pecivo
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    hmotnost varchar2(256),
    alergeny varchar2(256),
    druh varchar2(256)
);
CREATE TABLE predmet
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),
    druh varchar2(256),
    cena number,
    hmotnost varchar2(256)
);
CREATE TABLE objednavka
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    datum_objednani date DEFAULT current_date,
    stav    varchar2(256),
    cena    varchar2(256),
    doprava varchar2(256),
    termin_dodani   date
);
CREATE TABLE mnozstvi
(
  pocet number,
  druh varchar2(256)
);
CREATE TABLE vezen
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno varchar2(256),
    rodne_cislo number,
    pohlavi varchar2(256),
    cislo_cely number,
    trest varchar2(256)
);
CREATE TABLE smena
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    zacatek timestamp,
    konec timestamp,
    datum date,
    misto varchar2(256)
);
CREATE TABLE zamestnanec
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno varchar2(256),
    rodne_cislo varchar2(256) CHECK((LENGTH(rodne_cislo)=10 AND MOD(to_number(rodne_cislo), 11)=0) OR (LENGTH(rodne_cislo)=9 AND SUBSTR(rodne_cislo, 7,3) <> '000') AND REGEXP_LIKE(rodne_cislo, '^[[:digit:]]+$')
        AND (SUBSTR(rodne_cislo, 1, 2) >= 0 AND SUBSTR(rodne_cislo, 1, 2) <= 99) AND (SUBSTR(rodne_cislo, 3, 2) >= 1 AND SUBSTR(rodne_cislo, 3, 2) <= 12)
        AND (SUBSTR(rodne_cislo, 5, 2) >= 1 AND SUBSTR(rodne_cislo, 5, 2) <= 31)),
    pohlavi varchar2(256),
    ulice varchar2(256),
    cislo_popisne number,
    mesto varchar2(256),
    psc number,

    cislo_prukazu number,
    vycvik varchar2(256),
    vybaveni varchar2(256)
);

CREATE TABLE paserak
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno varchar2(256),
    rodne_cislo number,
    pohlavi varchar2(256)
);
CREATE TABLE vezeni
(
    id  number GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    nazev varchar2(256),

    ulice varchar2(256),
    cislo_popisne number,
    mesto varchar2(256),
    psc number
);

CREATE TABLE surovina_pecivo
(
    id_surovina number,
    id_pecivo number
);

CREATE TABLE pecivo_objednavka
(
    id_objednavka number,
    id_pecivo number
);

CREATE TABLE objednavka_vezen
(
    id_objednavka number,
    id_vezen number
);

CREATE TABLE objednavka_paserak
(
    id_objednavka number,
    id_paserak number
);

CREATE TABLE paserak_vezeni
(
    id_paserak number,
    id_vezeni number
);

CREATE TABLE vezeni_smena
(
    id_vezeni number,
    id_smena number
);
CREATE TABLE smena_zamestannec
(
    id_smena number,
    id_zamestnanec number
);

CREATE TABLE objednavka_predmet
(
    id_objednavka number,
    id_predmet number
);

INSERT INTO xsouce15.ZAMESTNANEC (jmeno, pohlavi, rodne_cislo)
VALUES ('idk', 'non-binary', '010101001');